contact/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views


app_name = 'contact'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),

    # contact (crud)
    path('contact/<int:contact_id>/details/', views.contact, name='contact'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),
    path('contact/create/', views.create, name='create'),

    # user (crud)
    path('user/register/', views.register, name='user/register'),
    path('user/login/', views.login_view, name='user/login'),
    path('user/logout/', views.logout_view, name='user/logout'),
    path('user/update/', views.user_update, name='user/update'),
]


# reconhece os arquivos estacios de static e media na BASE_DIR
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contact.urls'))
]

contact/forms.py
from contact.models import Contact
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import password_validation


class ContactForm(forms.ModelForm):
    # # (re)criando um campo (que ja existe)
    # first_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'placeholder': 'Mudou'
    #         }
    #     ),
    #     label='primeiro nome',
    #     help_text='texto de ajuda'
    # )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # ATUALIZANDO UM WIDGET QUE TENHO NO CAMPO
        # campos que tenho
        # self.fields['first_name'].widget.attrs.update({
        #     'placeholder': 'Escreva aqui'
        # })
        # self.fields['first_name'].label = 'teste'
        self.fields['picture'].widget = forms.FileInput(
            attrs={
                'accept': 'image/*'
            },
        )

    class Meta:
        model = Contact
        # campos que vao aparecer no form (que vem do model Contact)
        fields = (
            'first_name', 'last_name', 'phone',
            'email', 'description', 'category',
            'picture'
        )
        # https://docs.djangoproject.com/en/4.2/ref/forms/widgets/
        # CRIANDO UM WIDGET PRO CAMPO
        # widgets = {
        #     # nome do campo: 'widget que quero'
        #     'first_name': forms.TextInput(
        #         # atributos dentro da tag html
        #         attrs={
        #             'class': 'classe-a classe-b',
        #             'placeholder': 'Escreva aqui'
        #         }
        #     )
        # }

    # é chamado antes de enviar o formulario pro db
    # tem acesso a todos os campos
    def clean(self):
        cleaned_data = self.cleaned_data
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name == last_name:
            self.add_error(
                None,
                ValidationError(
                    'o campo First name e Last name mão pode ser iguais',
                    code='invalid'
                )
            )

        return super().clean()

    # clean_{nome_do_campo} é chamado automaticamente
    # e retorna o valor do campo
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        if first_name == 'ABC':
            raise ValidationError('nao runfo')
        return first_name


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2'
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError(
                    'já existe esse e-mail',
                    code='invalid'
                )
            )

        return email


class RegisterUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={
            'min_length': 'Please, add more than 2 letters.'
        }
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.'
    )

    password1 = forms.CharField(
        label="Senha",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label="Confirmação de senha",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text='Use the same password as before.',
        required=False,
    )

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username',
        )

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)

        password = cleaned_data.get('password1')

        if password:
            # cria senha no usuario de forma criptografada
            user.set_password(password)

        if commit:
            user.save()

        return user

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('Senhas não batem')
                )
        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if email != current_email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError(
                        'já existe esse e-mail',
                        code='invalid'
                    )
                )

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(errors)
                )

        return password1

contact/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context = {
        'title': 'Home'
    }
    return render(
        request,
        'contact/index.html',
        context
    )

contact/views/contact_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest
from contact.forms import ContactForm
from django.urls import reverse
from contact.models import Contact
from django.contrib.auth.decorators import login_required
from django.contrib import messages


@login_required(login_url='contact:user/login')
def create(request: HttpRequest):
    form_action = reverse('contact:create')
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)

        context = {
            # se o formulario ja ter sido respondido, vai passar o mesmo
            # formulario que ja foi respondido para que os campos
            # nao fiquem em branco
            'form': form,
            'title': 'Create Contact',
            'form_action': form_action
        }

        if form.is_valid():
            contact = form.save(commit=False)
            contact.owner = request.user
            contact.save()
            messages.success(request, 'Contato criado com sucesso')
            return redirect('contact:update', contact.id)

        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        # se apenas entrar na pagina, vai passar um formalario vazio
        'form': ContactForm(),
        'title': 'Create Contact',
        'form_action': form_action,
    }
    return render(
        request,
        'contact/create.html',
        context
    )


@login_required(login_url='contact:user/login')
def update(request: HttpRequest, contact_id):
    form_action = reverse('contact:update', args=(contact_id, ))
    contact = get_object_or_404(
        Contact,
        id=contact_id,
        show=True,
        owner=request.user
    )

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact)

        context = {
            # se o formulario ja ter sido respondido, vai passar o mesmo
            # formulario que ja foi respondido para que os campos
            # nao fiquem em branco
            'form': form,
            'title': 'Create Contact',
            'form_action': form_action
        }

        if form.is_valid():
            contact = form.save()
            messages.success(request, 'Contato alterado com sucesso')
            return redirect('contact:update', contact.id)

        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        # se apenas entrar na pagina, vai passar um formalario vazio
        'form': ContactForm(instance=contact),
        'title': 'Create Contact',
        'form_action': form_action,
    }
    return render(
        request,
        'contact/create.html',
        context
    )


@login_required(login_url='contact:user/login')
def delete(request, contact_id):
    contact = get_object_or_404(
        Contact,
        id=contact_id,
        show=True,
        owner=request.user
    )
    confirmation = request.POST.get('confirmation', 'no')
    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')

    page_title = f'{contact.first_name} {contact.last_name}'

    return render(
        request,
        'contact/contact.html',
        {
            'contact': contact,
            'title': page_title,
            'confirmation': confirmation
        }
    )

contact/views/contact_views.py
from django.shortcuts import render, redirect  # get_object_or_404
from django.db.models import Q
from contact.models import Contact
from django.http import Http404, HttpRequest
from django.core.paginator import Paginator


def index(request: HttpRequest):
    contacts = Contact.objects\
        .filter(show=True)\
        .order_by('-id')\

    # cria um paginator com 10 itens por pagina
    paginator = Paginator(contacts, 10)

    # o numero da pagina atual vai depender do search 'page' no url
    page_number = request.GET.get('page')

    # a lista de objs com base na pagina (cada pagina retorna 10 objs)
    page_obj = paginator.get_page(page_number)

    context = {
        'title': 'Home',
        'page_obj': page_obj
    }
    return render(
        request,
        'contact/index.html',
        context
    )


def search(request: HttpRequest):
    search_value = request.GET.get('q', '').strip()

    if not search_value:
        return redirect('contact:index')

    # iexact = exatamente o que tem escrito, sem considerar letras maisculas
    # exact = exatament o que tem escrito
    # contains = contem um trecho no campo
    # icontains = contem um techo no campo, sem considerar letras maisculas
    contacts = Contact.objects\
        .filter(show=True)\
        .filter(
            Q(first_name__icontains=search_value) |
            Q(last_name__icontains=search_value) |
            Q(email__icontains=search_value) |
            Q(phone__icontains=search_value)
        )\
        .order_by('-id')\
        # [10:20] = [limit:offset] na consulta

    # cria um paginator com 10 itens por pagina
    paginator = Paginator(contacts, 10)

    # o numero da pagina atual vai depender do search 'page' no url
    page_number = request.GET.get('page')

    # a lista de objs com base na pagina (cada pagina retorna 10 objs)
    page_obj = paginator.get_page(page_number)

    context = {
        'title': 'Home',
        'page_obj': page_obj
    }
    return render(
        request,
        'contact/index.html',
        context
    )


def contact(request, contact_id):

    single_contact = Contact.objects.filter(id=contact_id, show=True).first()

    # single_contact = get_object_or_404(
    #   Contact.objects.filter(id=contact_id).first()
    # )

    # metodo last retorna o ultimo elemento da queryset
    # metodo first retorna primeiro elemento da queryset

    if single_contact is None:
        raise Http404()

    page_title = f'{single_contact.first_name} {single_contact.last_name}'
    context = {
        'title': page_title or 'not found',
        'contact': single_contact
    }

    return render(
        request,
        'contact/contact.html',
        context
    )

contact/views/user_forms.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from contact.forms import RegisterForm, RegisterUpdateForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from django.contrib.auth.decorators import login_required


def register(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(
                request, 'Usuario criado com sucesso. Efetue o login'
            )
            return redirect('contact:user/login')
        context = {
            'title': 'Register',
            'form': form
        }
        return render(
            request,
            'user/register.html',
            context
        )
    context = {
        'title': 'Register',
        'form': RegisterForm()
    }
    return render(
        request,
        'user/register.html',
        context
    )


def login_view(request: HttpRequest) -> HttpResponse:
    form = AuthenticationForm(request)
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request, 'logado com sucesso')
            return redirect('contact:index')

    context = {
        'title': 'Login',
        'form': form
    }
    return render(
        request,
        'user/login.html',
        context
    )


@login_required(login_url='contact:index')
def logout_view(request):
    auth.logout(request)
    return redirect('contact:user/login')


@login_required(login_url='contact:user/login')
def user_update(request):
    form = RegisterUpdateForm(instance=request.user)

    if request.method != 'POST':
        return render(
            request,
            'user/update.html',
            {
                'form': form
            }
        )

    form = RegisterUpdateForm(data=request.POST, instance=request.user)

    if not form.is_valid():
        return render(
            request,
            'user/update.html',
            {
                'form': form
            }
        )

    form.save()
    messages.success(request, 'dados alterados com sucesso')
    return redirect('contact:user/update')

contact/templates/contact/contact.html
{% extends 'global/base.html' %}
{% block 'content' %} 
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{ contact.first_name }} {{ contact.last_name }}
        </h1>
        <p><b>ID:</b> {{ contact.id }}</p>
        <p><b>E-mail:</b> {{ contact.email }}</p>
        <p><b>Phone:</b> {{ contact.phone }}</p>
        <p><b>Created Date:</b> {{ contact.created_date }}</p>
        <p><b>Description:</b> {{ contact.description }}</p>
        <p><b>Category:</b> {{ contact.category.name }}</p>

        {% if contact.picture %}
            <p>
                <img src="{{ contact.picture.url }}" alt="picture {{ contact.first_name }} {{ contact.last_name }}">
            </p>
        {% endif %}

        {% if contact.owner == user %}
            <div class="contact-links">
                <a class='btn btn-link' href="{% url 'contact:update' contact.id %}">
                    Update
                </a>

                <form action="{% url 'contact:delete' contact.id %}" method='POST'>
                    {% csrf_token %}
                    {% if confirmation == 'no' %}
                        <input type="hidden" name="confirmation" value="yes">
                        <button class="btn btn-link btn-delete" type='submit'>
                            Confirma?
                        </button>         
                    {% else %}
                        <button class="btn btn-link btn-delete" type='submit'>
                            Delete
                        </button>
                    {% endif %}
                    
                </form>
                {% if confirmation == 'no' %}
                    <a class='btn btn-link btn-cancel' href="{% url 'contact:contact' contact.id %}">
                        Cancelar
                    </a>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock 'content' %}

contact/templates/contact/create.html
{% extends 'global/base.html' %}
{% block 'content' %}
    <div class="form-wrapper">
        <h2>Contact</h2>
        <form 
            action="{{ form_action }}" 
            method="POST" 
            enctype="multipart/form-data"
        >
            {% csrf_token %}

            <!-- por padrao form vem como .as_table -->
            <div class="form-content">
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">
                            {{ field.label }}
                        </label>
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help-text">
                                {{ field.help_text}}
                            </p>
                        {% endif %}
                    </div>
                    {% if field.name == 'picture' and field.value.url %}
                        <div class="form-group">
                            <img 
                                src="{{ field.value.url }}"
                                alt="picture {{form.first_name.value}} {{form.last_name.value}}"
                            />
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

            {% if form.non_field_errors %}
                <div class="form-content">
                    <div class="form-group">
                        <div class="message error">
                            {{ form.non_field_errors }}
                        </div>
                    </div> 
                </div>
            {% endif %}

            <div class="form-content">
                <div class="form-group">
                    <button class='btn' type="submit">Send</button>
                </div> 
            </div>
        </form>
    </div>
{% endblock 'content' %}

contact/templates/contact/index.html
{% extends 'global/base.html' %}

{% block 'content' %} 
    {% if page_obj %}
        <div class="responsive-table">
            <table class="contacts-table">
                <caption class="table-caption">
                    Contacts
                </caption>
                <thead>
                    <tr class="table-row table-row-header">
                        <th class="table-header">
                            id
                        </th>
                        <th class="table-header">
                            First Name
                        </th>
                        <th class="table-header">
                            Last Name
                        </th>
                        <th class="table-header">
                            Phone
                        </th>
                        <th class="table-header">
                            E-mail
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for contact in page_obj %}
                        <tr class='table-row'>
                            <td class='table-cel'>
                                <a 
                                    href="{% url 'contact:contact' contact.id %}"
                                    class="table-link"
                                >
                                    {{ contact.id }}
                                </a>
                            </td>
                            <td class='table-cel'>
                                {{ contact.first_name }}
                            </td>
                            <td class='table-cel'>
                                {{ contact.last_name }}
                            </td>
                            <td class='table-cel'>
                                {{ contact.phone }}
                            </td>
                            <td class='table-cel'>
                                {{ contact.email }}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div clas='single-contact'> 
            <h1 class='single-contact-name'> 
                Nenhum contato encontrado
            </h1>
        </div>
    {% endif %}
{% endblock 'content' %}